feat: support holesky
ralexstokes/ethereum-consensus pull request #218
Opened 2023-08-25 18:51 UTC by chirag-bgh

Closes #216

2023-08-25 19:09 UTC, chirag-bgh commented
@ralexstokes where can I find exact values for like `MIN_GENESIS_ACTIVE_VALIDATOR_COUNT` etc?

2023-08-30 21:41 UTC, ralexstokes requested changes
thanks for this!

left a few things to fix but then this is ready to merge

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/clock.rs
> +pub const HOLESKY_GENESIS_TIME: u64 = 1694786100;
```suggestion
pub const HOLESKY_GENESIS_TIME: u64 = 1694786400;
```

genesis time is `MIN_GENESIS_TIME` and at least `GENESIS_DELAY`

bc of how we are starting the network, we know ahead of time what the genesis time will be

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/state_transition/context.rs
> +        let bellatrix_preset = &bellatrix::minimal::PRESET;
refer: https://github.com/eth-clients/holesky/blob/main/custom_config_data/config.yaml#L2

```suggestion
        let phase0_preset = &phase0::mainnet::PRESET;
        let altair_preset = &altair::mainnet::PRESET;
        let bellatrix_preset = &bellatrix::mainnet::PRESET;
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +// Genesis delay 5 seconds
```suggestion
// Genesis delay 5 minutes
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +pub const EJECTION_BALANCE: Gwei = 16 * 10u64.pow(9);
https://github.com/eth-clients/holesky/blob/main/custom_config_data/config.yaml#L61

```suggestion
pub const EJECTION_BALANCE: Gwei = 28 * 10u64.pow(9);
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +pub const DENEB_FORK_VERSION: Version = [4, 0, 16, 32];
https://github.com/eth-clients/holesky/blob/main/custom_config_data/config.yaml#L37

```suggestion
pub const DENEB_FORK_VERSION: Version = [64, 1, 112, 0];
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +// MAX_REQUEST_BLOCKS_DENEB*MAX_BLOBS_PER_BLOCK
```suggestion
// MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +    // 0
```suggestion
```

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +pub const BLOB_SIDECAR_SUBNET_COUNT: u64 = 6;
if we don't need these right here, I'd just leave them out of this PR

if anything they would end up w/ the networking code

2023-08-30 21:41 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +    let terminal_total_difficulty = 0u64.into();
this works but I think this is a bit more expressive

```suggestion
    let terminal_total_difficulty = U256::zero();
```

2023-09-08 14:18 UTC, ralexstokes commented on ethereum-consensus/src/clock.rs
> +pub const HOLESKY_GENESIS_TIME: u64 = 1694786100;
can you please update the constant?

2023-09-08 14:25 UTC, ralexstokes requested changes
looks good! one nitpick on the imports formatting

2023-09-08 14:25 UTC, ralexstokes commented on ethereum-consensus/src/configs/holesky.rs
> +};
let's keep imports all together

```suggestion
use ssz_rs::U256;
use crate::{
    configs::Config,
    primitives::{Epoch, ExecutionAddress, Gwei, Version, FAR_FUTURE_EPOCH},
};
```

2023-09-08 14:30 UTC, ralexstokes requested changes
one more thing on import

2023-09-08 14:55 UTC, chirag-bgh commented on ethereum-consensus/src/configs/holesky.rs
> +};
Done!

2023-09-08 15:06 UTC, ralexstokes approved these changes

2023-09-08 15:07 UTC, merged